#!/bin/env ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "opscode_ubuntu-12.04_chef-11.2.0"
  config.vm.network :forwarded_port, guest: 80, host: 8080
  # config.vm.network :private_network, ip: "192.168.33.10"
  # config.vm.network :public_network

  config.vm.provision :shell, :inline => 'apt-get update'
  
  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = "../../cookbooks"
    chef.roles_path     = "../../roles"
    chef.data_bags_path = "../../data_bags"
    
    chef.add_recipe "webapp::default"
    # chef.add_role "web"
  
    # chef.json = { :mysql_password => "foo" }
  end
end
